### ISSUE TITLE
JKS format

### ISSUE THREAD

**Issue by vmavromatis** [datatrans/techinfo.datatrans.ch#1]
Dear Datatrans team,

Our API gateway is asking for the certificates to be in JKS format. Is it possible to provide them in this format? The certificate I'm interested in is PCI-proxy. Thank you very much in advance.

Kind regards,
Vasilis

**Comment by dmengelt** [comment]
hi @vmavromatis 

what is the reason the API gateway needs this? if they use the default java key store (cacerts) this should be perfectly fine. If still needed, please let me know for which domains you need it.

**Comment by vmavromatis** [comment]
@domi55 thank you for the prompt response. 

Our affected domain is secure.interface-xml.com and the corresponding certificate is api.pci-proxy.com. I have already given them the .pem files but they insist on JKS format. Thank you so much for helping us.

Regards

**Comment by dmengelt** [comment]
But then this should be easy. They can just convert with
```
openssl x509 -in cert.pem -inform PEM -out cert.der -outform DER 
keytool -import -keystore keystore.jks -storepass "foobar" -file cert.der
```

**Comment by vmavromatis** [comment]
Thank you @domi55. Can you please elaborate on which one is cert.pem? (I see 3) and what does foobar refer to? A password defined by ourselves or datatrans? Thank you very much.

**Comment by dmengelt** [comment]
hello @vmavromatis 
this has nothing todo with datatrans.
also. there is only one `cert.pem` ;) The other one is `cert.der` whis is created by the first `openssl` command. Then `keystore.jks` is the current keystore your API Gateway already has. `foobar` is the password of the keystore from the API Gateway.

**Comment by vmavromatis** [comment]
Thank you for the info. I'm passing this to the sysadmin. You may now close this ticket.
